### ISSUE TITLE
Questions about the "Pool=50K" in your paper.

### ISSUE THREAD

**Issue by DLiquor** [hkust-nlp/deita#12]
Hi, thanks for your work! I have some questions about your experiment in training the complexity scorer.   

> “Pool=50K” denotes the data selection procedure is conducted in a 50K-sized subset due to the cost of using ChatGPT to annotate the entire pool."

1、The data used for "EVOL COMPLEXITY (Pool=50K)" is sampled from 50K samples while that for "EVOL COMPLEXITY" is sampled from the original data pool? 
2、How do you sample the data from the original data pool?
Hope for your reply!

**Comment by VPeterV** [comment]
Hi, thank you for your interest, and I apologize for the delayed response.

1. The data for "EVOL COMPLEXITY (Pool=50K)" consists of 50,000 samples randomly sampled from the original dataset. Due to the high cost of using ChatGPT, we had to sample a subset of the data to enable a fair comparison with the results obtained using the direct scoring method, which relies on ChatGPT.
2. We randomly sampled this data from the original dataset.

Please do not hesitate to contact us if you have any further questions.

**Comment by VPeterV** [comment]
Close this issue for now. If you have any additional questions or concerns, please don't hesitate to reopen it.
