### ISSUE TITLE
Have you conducted ablation experiments with three factors: Complexity, Quality, and Diversity? Which one has the greatest impact on performance improvement?

### ISSUE THREAD

**Issue by 447428054** [hkust-nlp/deita#22]
Have you conducted ablation experiments with three factors: Complexity, Quality, and Diversity? Which one has the greatest impact on performance improvement?

**Comment by VPeterV** [comment]
Hi, thx for ur interest!

I believe the comparisons you're referring to can be found in sections 2.2 to 2.5 of our paper. Regarding "the greatest impact factor", our experience suggests that each factor needs to be integrated with others to maximize potential. For example, focusing solely on diversity in sample selection won't necessarily yield samples with the highest complexity or quality. Conversely, prioritizing complexity without considering diversity can lead to suboptimal performance due to redundancy in the selected subset.
